### ISSUE TITLE
Script input from pipeline

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#1]
```console
$ echo "1+2" | ./erg
Erg 0.1.0 (tags/?:8a62e0f, 2021/09/13 17:11:40.30) on x86_64/windows
Type "help!()", "copyright", "credits" or "license" for more information.
'>>>' 3
'>>>'
```

When I try to pass a script from the pipeline, I get this message: it seems to start in REPL mode.
I don't know how to distinguish between the stdin types in Rust.

**Comment by KisaragiEffective** [comment]
Hi! I know how to handle this. You can use [`atty`](https://lessis.me/atty/atty/index.html) crate.
Here's an example code:

```rs
let piped_from_stdin = atty::is(atty::Stream::Stdout);
```

May I send a PR for this issue? Thank you.

**Comment by KisaragiEffective** [comment]
I've submitted PR.
