### ISSUE TITLE
Type inference is wrong for mutable types

### ISSUE THREAD

**Issue by ytoml** [erg-lang/erg#107]
**Describe the bug**
Valid declaration of mutable object encounter `TypeError`.
``

**Reproducible code**
In REPL:
```
Erg interpreter 0.3.2 (tags/?:, 2022/08/31 08:13:23) on aarch64/macos
>>> i: Int! = !100
Error[#0048]: File <stdin>, line 1, in <module>
1│ i: Int! = !100

   ^
TypeError: the type of i is mismatched:
expected:  Int!
but found: Nat!
```

**Expected behavior**
Assignment above should be accepted.

**Comment by ytoml** [comment]
I could fix this problem with modification in `Context::cheap_supertype_of()` in `compare.rs` like:
```Rust
match (lhs, rhs) {
    /* omit */
    (Type::MonoClass(l), Type::MonoClass(r))
        if matches!(l.chars().last(), Some('!'))
            && matches!(r.chars().last(), Some('!')) =>
    {
        self.cheap_supertype_of(
            &Type::from(&l[..l.len() - 1]),
            &Type::from(&r[..r.len() - 1]),
        )
    }
   /* omit */
}
```
but there left another problem where left hand side of
```
i: Int! = !100
```
is actuallly evaluated as `Nat!`.

**Comment by mtshiba** [comment]
There is only a nominal relationship between type `T!` and type `T`. So `Nat!` is a subclass of `Nat`. There are no further structural relationships. 

Since, for example, it is nonsense to require a type that must be inherently mutable to have a corresponding immutable type.

**Comment by mtshiba** [comment]
The cause of this bug was that I forgot to add `Int!` to the superclass list of `Nat!`. In addition, `Bool!` is also a subclass of `Nat!` and `Int!`. Just fix the following in `init_builtin_classes` in `initialize/mod.rs`.

![スクリーンショット 2022-09-01 142554](https://user-images.githubusercontent.com/45118249/187838200-70b38cd2-35be-44fb-a6f4-09c69785405b.png)

**Comment by ytoml** [comment]
I see, thanks! I will submit PR later.
