### ISSUE TITLE
Commutative arithmetic operation with `Bool` behaves different when order is different

### ISSUE THREAD

**Issue by ytoml** [erg-lang/erg#110]
**Describe the bug**
When trying to some commutative arithmetic operations (like `+`, `*`)with `Bool`, we cannot do it if `Bool` value is in left hand side.

**Reproducible code**
```
Erg interpreter 0.3.2 (tags/?:2143343, 2022/09/01 15:00:27) on aarch64/macos
>>> 1 + True
2
>>> True + 1
Error[#0613]: File <stdin>, line 1, in <module>
1│ True + 1

   ^^^^^^^^
TypeError: the type of `+`::lhs is mismatched:
expected:  ?L(<: Add(?R(: Type (:> Never, <: Obj))[0])(cyclicity: Not))[0]
but found: {%v14: Bool | %v14 == True}
```

**Comment by mtshiba** [comment]
I solved this problem by implementing `Add(Bool)` on `Bool`, but I have found another problem related to this.
I will start another issue.
