### ISSUE TITLE
Please set the English document as the initial document instead of the Japanese document

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#116]
The label of translation synchronization should be added to the Japanese document after the English document is completely translated 

When the content of the document needs to be changed, the English document should be changed, otherwise too many contributors will be restricted

And it is not convenient to track translation

Depend on the completion of https://github.com/erg-lang/erg/issues/119

**Comment by mtshiba** [comment]
Yeah, the English version should be the standard.

However, I am in the process of rewriting the entire document due to grammar changes. Once the update is complete, we will remove badges from the English version and put them on the Japanese version.
