### ISSUE TITLE
Erg book navigation links at the bottom (Prev|Next) are broken

### ISSUE THREAD

**Issue by KtlTheBest** [erg-lang/erg#16]
The links at the bottom refer to "XX_chaptername.md" while the correct one should be "XX_chaptername.html".

The navigation can still be used via the side-bar chapter links, but it may cause inexperienced people to think that the chapter is missing or not implemented.

**Comment by KtlTheBest** [comment]
It is also the same for the Japanese version of the book as far as I can tell.

**Comment by mtshiba** [comment]
I already know the problem.
I use [mdbook](https://github.com/rust-lang/mdBook) to made my documents into books. Apparently this software doesn't recognize links correctly when using html elements.

Originally this `Prev|Next` was set up for people looking at documentation from GitHub. In the case of the Book, there is a navigation bar, so I thought it would be good to use that.
It seems that I need to delete `Prev|Next` from the Book or fix it manually, but is there any good way?
Or is this a better issue to report to mdbook?

**Comment by soukouki** [comment]
How about mechanically removing `Prev|Next` forms before processing of the mdbook?
This is an ad hoc response, but it could be used as a measure in the meantime.

**Comment by mtshiba** [comment]
This issue was solved https://github.com/erg-lang/erg-lang.github.io/pull/2 .
