### ISSUE TITLE
REPL crash

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#163]
**Describe the bug**
![image](https://user-images.githubusercontent.com/62678643/195860452-789c026e-17a1-4613-bfd2-16b89bb057ff.png)

**OS**
Windows 11

**Comment by mtshiba** [comment]
I reproduced this problem also on Ubuntu. The cause is that `erg` does not have permission to write files to the current directory (Erg writes a .pyc file and makes Python read it).
