### ISSUE TITLE
do! is not defined

### ISSUE THREAD

**Issue by markjreed** [erg-lang/erg#21]
Code from the README:

    2.times! do!:
        print! "hello, ", end: ""

Result: 

    1│ 2.times! do!:
                ^^^
    NameError: do! is not defined

erg v0.2.2 installed on macOS 12.5 via rustup-installed cargo 1.63.0

**Comment by mtshiba** [comment]
This is a feature that has not yet been implemented. Since `do:` is just a syntax sugar for `() ->`, please use that for a while.

**Comment by mtshiba** [comment]
But with `() ->`, I seem to get a SyntaxError this time. I will fix it.

**Comment by mtshiba** [comment]
Fixed in https://github.com/erg-lang/erg/commit/f847029e1658adb8da0d682d79bad10e3a95bbef.
