### ISSUE TITLE
Problem of `.pyc` write permission

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#216]
### Describe the bug?

![image](https://user-images.githubusercontent.com/62678643/197328785-a1391464-a35d-4a8e-8360-ee6037515b1b.png)

### Erg version

Erg 0.5.10

### Python version

Python 3.10.5

### OS

Windows 11

**Comment by mtshiba** [comment]
same as #163?

**Comment by C-BJ** [comment]
yeah, But it seems that there is no problem in main branch

**Comment by C-BJ** [comment]
There is no problem in some directories, but there is a problem in some directories. It seems to be a problem with the `.pyc` write permission @mtshiba

**Comment by C-BJ** [comment]
I can solve this problem with administrator permission

**Comment by C-BJ** [comment]
Can `.pyc` be automatically deleted at the end of the run (including when it crashes)?

**Comment by mtshiba** [comment]
> Can `.pyc` be automatically deleted at the end of the run (including when it crashes)?

Done. https://github.com/erg-lang/erg/commit/22857229ee75d7bfae9ea6c8996b5949c26c90ba
