### ISSUE TITLE
Confused by apparently duplicate syntaxes (might just be a docs issue)

### ISSUE THREAD

**Issue by lahwran** [erg-lang/erg#23]
Hey! Erg looks really cool. However, my one big hesitancy with it from a language design perspective is that there are multiple endorsed ways to do the same thing that appear to not be consequences of composition of features. eg,

> Functions can be declared in four different ways. None of them can omit the return type.
> ```
> f(x: Int, y: Int): Int
> f(Int, Int): Int
> f: (x: Int, y: Int) -> Int
> f: (Int, Int) -> Int
> ```

I'm not sure if I'm misunderstanding the docs here. Maybe there's some equivalence between `: ` and `->` that makes them related, and instead of remembering "there are several ways to write function definitions", I should remember "colon is usually optional on one line" or something along those lines.

it's also pretty unclear to me why these are equivalent:

> functions are invoked like f x, y, ..., but if there are too many arguments for a single line, they can be applied using : (colon).
> ```
> f arg1 + arg2, arg3 * arg4
> ```
> 
> ---
> ```
> f arg1 + arg2:
>     arg3 * arg4
> ```
> ---
> ```
> f:
>     arg1 + arg2
>     arg3 * arg4
> ```

coming from python, I would have expected this to either define a function with no arguments `f()`, or perhaps coming from yaml, pass a list. but the middle invocation is very confusing to me - we're splitting the parameter list with a colon. why is that equivalent? this seems like it might merely be a documentation issue and that there's an underlying consistency that would make it make sense, but the docs didn't get to that point quickly, and the result is that the language looks like it has redundant syntax to my brain.

Just some commentary cuz I found the language while browsing github. Looks like a fun project!

**Comment by mtshiba** [comment]
First, I am thinking of deprecating the `f(x: Int, y: Int): Int` grammar. It seems difficult to parse, and even harder for humans to distinguish from a function call.

Next, `f: (x: Int, y: Int) -> Int` and `f: (Int, Int) -> Int` are clearly distinguished in the type system. The former is a function type with parameter names, and the latter is a function type without parameter names. The latter cannot be called with keyword arguments.

The last example is a way to avoid increasing grammar.
For example,

```python
match x, (1 -> ...), (2 -> ...), ...
```

is same as

```python
match x:
    1 -> ...
    2 -> ...
    ...
```

So Erg does not need to add `match` syntax, `match` is just a function.

However,  `f x, y, z, ...` to

```python
f x:
    y
    z
```

conversion seems to treat `x` specially compared to the other arguments. For some functions, there is no need to treat the first argument specially at all.

Therefore,

```python
f:
  x
  y
  z
```

is also valid.
