### ISSUE TITLE
REPL does not support multi-line errors

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#248]
### Describe the bug?

A block is created in the REPL, and if there is an error there, a blank line is displayed.

### Reproducible code

```
>>> for! 0..5,i -> 
...    print! i
```

### Expected result

```
1 | for! 0..5, i -> 
  :            -
2 |    print! i
  : -----------
  :           |- expected: (?T(: Type)) => NoneType
  :           `- but found: (i: ?3(<: Ref(Obj))) -> NoneType
```

### Actual result

```
1 | 
  :           -
2 | 
  : -----------
  :           |- expected: (?T(: Type)) => NoneType
  :           `- but found: (i: ?3(<: Ref(Obj))) -> NoneType
```

### Additional context

The REPL uses `reread()`
```rust
    let codes = if e.input().is_repl() {
        vec![e.input().reread()]
    } else {
        e.input().reread_lines(ln_begin, ln_end)
    };
```
However, this only gets the last element
```rust
    pub fn reread(&self) -> String {
        self.buf.last().cloned().unwrap_or_default()
    }
```
REPL exits the block if there is only a newline
So the last element will be a newline only
Perhaps that is what it shows

### Erg version

0.5.12

**Comment by mtshiba** [comment]
The constant `GLOBAL_STDIN` holds all standard input received.
`reread_lines(x, y)` is simply returns `buf[x - 1 . = y - 1]`, but since the REPL resets the number of lines each time, a new method should be implemented for that.

**Comment by C-BJ** [comment]
Should this be closed?

**Comment by GreasySlug** [comment]
@C-BJ 
Yes, thank you
