### ISSUE TITLE
Arrow keys are not working in REPL

### ISSUE THREAD

**Issue by ktny** [erg-lang/erg#26]
Left arrow key would be typed `^[[D` in REPL.
The other arrow keys are the same, so I cannot enter previous input value with up arrow key.

```sh
❯ erg
Starting the REPL server...
Connecting to the REPL server...
Retrying to connect to the REPL server...
Erg interpreter 0.2.2 (tags/?:, 2022/08/14 20:25:00) on x86_64/linux
>>> print!()^[[D
```

erg v0.2.2 installed on wsl2 on windows11 via rustup-installed cargo 1.62.1

**Comment by mtshiba** [comment]
I am aware of the problem as well. It appears that Erg need to handle the input. That can be somewhat tedious.
It looks like [termion](https://gitlab.redox-os.org/redox-os/termion/-/blob/master/Cargo.toml) crate could be used to solve this issue. I will use this to solve the problem for a while.
