### ISSUE TITLE
Some links of Erg book index are broken

### ISSUE THREAD

**Issue by soukouki** [erg-lang/erg#28]
http://mtshiba.me/TheErgBook/indexes.html

Examples:
`print!` link leads page that is not exist (404 File not found).
`Self` link liads page that is not exist (404 Document not found).

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**

**Comment by C-BJ** [comment]
When you don't get a reply, you should come to discord and ask questions or just attach a link @KetanParmar07
