### ISSUE TITLE
Include the language server

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#294]
Currently, [Erg Language Server](https://github.com/erg-lang/erg-language-server) is isolated from the compiler itself. This is to avoid compile time and binary size bloat.

However, in this case, updating the compiler and updating the server is a double effort, so we would like to be able to include the language server feature as an optional feature.

**Comment by toddlerer** [comment]
I think it's good.
The language server is almost indispensable for development, and with no convenient package management tool or third-party language server available, it would be easier to update the language server by simply updating `erg`.
