### ISSUE TITLE
RuntimeError: Bad code object in .pyc file

### ISSUE THREAD

**Issue by stasoid** [erg-lang/erg#296]
### Describe the bug?

Erg fails with `RuntimeError: Bad code object in .pyc file` and deletes code file:
```
$ echo 'print!0' > tst
$ cat tst
print!0
$ erg tst
RuntimeError: Bad code object in .pyc file
$ cat tst
cat: tst: No such file or directory
```
I tried other versions, 0.5.8 is the latest version that I am able to compile that doesn't have this bug:
```
0.5.12 this error
0.5.11 this error
0.5.10 build error
0.5.9  build error
0.5.8  good
```

### Erg version

0.5.13
also tested latest dev version

### Python version

3.8.10

### OS

Ubuntu 20.04 (On Windows 10 through WSL2)

**Comment by mtshiba** [comment]
This is probably due to the use of an unsupported version of Python (Erg supports CPython 3.8, 3.10~3.11).
Could you tell me what version of Python you used?

**Comment by mtshiba** [comment]
This script ran successfully in Python 3.10 and 3.11. Although not explicitly stated in the documentation, Python 3.8 is "tier 2 support", which is more unstable than 3.10 or 3.11.

We will work on fixing this, but for the time being, please run Erg using the Python version shown above.

**Comment by mtshiba** [comment]
The bug that caused files to be deleted when no extension was added has been fixed.

**Comment by stasoid** [comment]
Yes, it works with Python 3.11, thank you.
