### ISSUE TITLE
Crashes when running an erg command with no valid parameters entered

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#333]
### Describe the bug?

![image](https://user-images.githubusercontent.com/62678643/210695339-d3328cc2-e8a2-4a3a-b8ac-1eb77b419ce9.png)

### Erg version

0.6.1

### Python version

Python3.11.x

### OS

Windows 11

**Comment by C-BJ** [comment]
Actually, I'm not sure what this command does

**Comment by mtshiba** [comment]
This command specifies how many seconds to wait for REPL output. The default is 10 seconds.

This option requires an argument. You did not pass any arguments, so an error was returned.
But this should be exit, not panic.

**Comment by C-BJ** [comment]
I see

**Comment by C-BJ** [comment]
I think it can stay that way for now
