### ISSUE TITLE
Git hash tags in REPL disappear

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#344]
### Describe the bug?

![image](https://user-images.githubusercontent.com/62678643/211178384-5ff6219e-5c52-40ff-b167-f6d16e601e01.png)

### Erg version

0.6.1

### Python version

Python3.11.x

### OS

Windows 11

**Comment by mtshiba** [comment]
I think this isn't Erg's problem but a problem with git installed in your computer.

**Comment by C-BJ** [comment]
> I think this isn't Erg's problem but a problem with git installed in your computer.

But I installed it via cargo

**Comment by mtshiba** [comment]
The build script runs `git rev-parse --short HEAD` to get the git hash number. Erg just shows the result.

**Comment by C-BJ** [comment]
I install it from the cargo. Is there no git information causing this error?

> The build script runs `git rev-parse --short HEAD` to get the git hash number. Erg just shows the result.
