### ISSUE TITLE
`Write error` occurs when invalid array declaration

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#357]
### Describe the bug?

Arrays can be declared with length specifications
The compilation succeeds, but a `Write error` is received

### Reproducible code

```
[Int; 1]
```
```
[1; 1]
```

### Expected result

Above is success, below is error

### Actual result

Write error: 既存の接続はリモート ホストに強制的に切断されました。 (os error 10054)
error: process didn't exit successfully: `target\debug\erg.exe` (exit code: 1)     

### Erg version

Erg 0.6.2-nightly.1

### Python version

Python3.11.x

### OS

Windows 10

**Comment by mtshiba** [comment]
`[x; n]` is a shorthand for `[x, x, x, ...]`.

i.e. `[Int; 2] == [Int, Int]`, `[1; 2] == [1, 1]`

`[1; 2]` does not work properly, I fixed.
