### ISSUE TITLE
Parallel eval all result in the same processing

### ISSUE THREAD

**Issue by toddlerer** [erg-lang/erg#370]
### Describe the bug?

```bash
erg -c "print! 1" & erg -c "print! 2"
```
the result is
```
1
1
```

As a workaround, the problem is resolved by adding a hash value to the dumped pyc filename.

### Erg version

Erg 0.6.3

### Python version

Python3.11

### OS

macOS 12 (Monterey)

**Comment by mtshiba** [comment]
In case of `-c` option, the name of the dumped pyc file will be `stdin.pyc`. Since the hash value of the same string will still be the same, it is necessary to add a random suffix to the filename.
