### ISSUE TITLE
Organize crates

### ISSUE THREAD

**Issue by cm-ayf** [erg-lang/erg#4]
Currently, following crates are found:
- erg_common: `/src/erg_common`
- erg_compiler: `/src/erg_compiler`
- erg_parser: `/src/erg_compiler/erg_paraser`

These crates should be organized in a good manner; for example, create `/workspaces/` (or `/complier/`?) and put all crates there.

Also, these crates should be managed by Cargo's workspace feature.

refer to: [rust-lang/rust](/rust-lang/rust) directory structure

**Comment by mtshiba** [comment]
I created the `organize_crates` branch and added the workspace.
This looks good, Rust-analyzer can now detect errors in the `erg_parser` test file.

Thank you for your suggestion.

**Comment by mtshiba** [comment]
#
