### ISSUE TITLE
parser causes panic when in debug mode

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#400]
### Describe the bug?

Parsing EOF with Parser may consume EOF in rare cases
This causes a panic because it cannot get the token with `debug_exit_info!`

### Reproducible code

cargo dprs

```
a = (
    1
```
```rust
                let rparen = self.lpop(); <- consume EOF
                if let Expr::Tuple(Tuple::Normal(tup)) = &mut expr {
                    tup.elems.paren = Some((lparen, rparen));
                }
```

### Expected result

Syntax error

### Actual result

panic

### Erg version

0.6.4

### Python version

Python3.11

### OS

Windows 10

**Comment by mtshiba** [comment]
I fixed this issue and introduced a useful macro `expect_pop!`.

This macro expects a specific token at the current position and returns an error if not.
