### ISSUE TITLE
REPL: unexpected exception is thrown 

### ISSUE THREAD

**Issue by Hanaasagi** [erg-lang/erg#419]
### Describe the bug?

Enter the REPL, and type `assert 1 == 2`

```
>>> assert 1 == 2
Traceback (most recent call last):
  File "<string>", line 32, in <module>
  File "<string>", line 1, in <module>
  File "<stdin>", line -1, in <module>
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 36, in <module>
NameError: name 'e' is not defined
```

A `NameError: name 'e' is not defined` is thrown, this is not expected. And REPL is not worked after this exception. E.g. type `print!("hello")`, no text is displayed.

### Reproducible code

```
assert 1 == 2
```

### Expected result

No `NameError` here.

### Actual result

![2023-04-22_13-00](https://user-images.githubusercontent.com/9482395/233763503-12f71c91-c8d9-4a43-b956-27090d52671c.png)

### Erg version

main branch, commit hash is fb294fa991beebdb2a4445173ac4d77470e2c677

### Python version

Python3.10

### OS

Linux (other distro)

**Comment by anzhi0708** [comment]
I had the same problem
