### ISSUE TITLE
Terminal cursor shape is changed and not reset when exit REPL

### ISSUE THREAD

**Issue by Hanaasagi** [erg-lang/erg#428]
### Describe the bug?

Compiled erg wiht `full-repl` features. Enter the REPL and exit, the cursor shape is changed to `Line` type.

### Reproducible code

Change the cursor type in the terminal to `block` type. Enter the REPL and then exit.

### Expected result

Not changed.

### Actual result

Chagned.

### Additional context

I think this line is unneeded.

https://github.com/erg-lang/erg/blob/a6db8b94bdc7ec83f1e6fd7fe3fef6280975718a/crates/erg_common/stdin.rs#L106

### Erg version

main branch

### Python version

None

### OS

None

**Comment by mtshiba** [comment]
@C-BJ What was your intention in making the shape of the cursor a line at this point?
Are there any problems with removing it?

**Comment by mtshiba** [comment]
And, I see that `SetCursorShape` has been removed in the latest `crossterm` (v0.26.1).

**Comment by Hanaasagi** [comment]
In v0.26.1, `SetCursorStyle` has replaced `SetCursorShape`.

**Comment by C-BJ** [comment]
> @C-BJ What was your intention in making the shape of the cursor a line at this point?
> 
> https://github.com/erg-lang/erg/blob/a6db8b94bdc7ec83f1e6fd7fe3fef6280975718a/crates/erg_common/stdin.rs#L106
> 
> Are there any problems with removing it?

There should be no problem deleting it, I think I've forgotten the reason for doing so in the first place.
