### ISSUE TITLE
Unified exit keybinding in REPL

### ISSUE THREAD

**Issue by Hanaasagi** [erg-lang/erg#429]
Type `exit` in REPL, we will see

```
Use exit() or Ctrl-D (i.e. EOF) to exit
```

This is a message from Python interpreter.

- When compiled without `--features full-repl`, `Ctrl-d` does not work. we need to use `Ctrl-c` to exit.

- When compiled with `--features full-repl`, `Ctrl-c` has no effect, and `Ctrl-d` doesn't work either. We need to use `Ctrl-z`.

https://github.com/erg-lang/erg/blob/379caacce90dbeb41ad7400e1709a2f829d55b2a/crates/erg_common/stdin.rs#L126-L132

This inconsistent behavior is quite confusing.

**Comment by mtshiba** [comment]
At least, the REPL should be able to exit with Ctrl-D when built with `--features full-repl`.

**Comment by Hanaasagi** [comment]
> At least, the REPL should be able to exit with Ctrl-D when built with --features full-repl.

Yes, I think so.

>  Without full-repl, it should modify messages from Python.

In a terminal environment, Ctrl-D tmeans EOF, indicating that the user has no more input. I tested the behavior of following REPL. I don't think the message needs to be modified. Using Ctrl-D to exit seems to be a convention.

<table>
<tr>
 <td> key
 <td> python
 <td> node
 <td> ghci
 <td> irb
<tr>
 <td> ctrl-d
 <td> exit
 <td> exit
 <td> exit
 <td> exit
</table>

**Comment by C-BJ** [comment]
![image](https://github.com/erg-lang/erg/assets/62678643/4c5db366-7ca5-405d-be45-65198e41ba11)

**Comment by C-BJ** [comment]
Maybe support Ctrl + D/Z at the same time
