### ISSUE TITLE
Name resolution for external libraries

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#430]
### Describe the bug?

If you place a .er file in any directory and run an external library, the name will have the name of that directory in the name

### Reproducible code

- main.er and src/main.er
```
glob = pyimport "glob"
matplotlib = pyimport "matplotlib"
_ = matplotlib.pyplot.plot!([1, 2, 3, 4, 5])
_ = matplotlib.pyplot.xlabel!("x label")
_ = matplotlib.pyplot.ylabel!("y label")
_ = matplotlib.pyplot.title!("figure title")

matplotlib.pyplot.show!()
print! glob.glob!("*")
```

- directory structure
erg_venv/
|- Scripts
|- Share
|- Lib
|- Include
|- src/main.er
` main.er

matplotlib is installed

```shell
erg .\main.er
erg .\src\main.er
```

### Expected result

A plot pops up and the following is displayed
```
['Include', 'Lib', 'main.er', 'main.er_1451371705875309023.pyc', 'Notebooks', 'pyvenv.cfg', 'Scripts', 'share', 'src']
```

### Actual result

- erg .\main.er
```
erg .\main.er
['Include', 'Lib', 'main.er', 'main.er_13256591462810537566.pyc', 'Notebooks', 'pyvenv.cfg', 'Scripts', 'share', 'src']
```

- erg .\src\main.er
```
erg .\src\main.er
Traceback (most recent call last):
  File ".\src\main.er", line -1, in <module>
ModuleNotFoundError: No module named 'src.matplotlib'
```

### Erg version

Erg 0.6.14-nightly.2

### Python version

Python3.11

### OS

Windows 11

**Comment by mtshiba** [comment]
I fixed the bug, but in this case Erg doesn't load the module under `erg_venv/Lib` unless you explicitly add the path to `sys.path`.
