### ISSUE TITLE
Cargo build error

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#45]
![image](https://user-images.githubusercontent.com/62678643/185126159-5a0ad62c-3103-4b93-8a86-1c698e42c659.png)

Windows 11 1000.22000.652.0
Rust 1.63.0
Erg main or 0.2.5

**Comment by mtshiba** [comment]
It seems to be failing to decode the build time.
From which CLI did you perform the build?

```console
cmd /C "echo %date% %time%"
```

And please run the above command and let me show the results.

**Comment by C-BJ** [comment]
![image](https://user-images.githubusercontent.com/62678643/185142920-bf8f1ca3-f5b5-4487-91f4-33689df8eb59.png)
@mtshiba

**Comment by mtshiba** [comment]
Maybe the cause may be in the Chinese characters.
I'll see what I can do.

**Comment by mtshiba** [comment]
For now, characters that fail to parse are displayed as �.

https://github.com/erg-lang/erg/commit/6921189a953b7e0535e432cb83f65edda37e6983

But is there any essential solution?

**Comment by mtshiba** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=37ce1e8f485b80ec4c99020ab8b1094f

Chinese characters should be able to be parsed.

**Comment by C-BJ** [comment]
https://github.com/erg-lang/erg/commit/6921189a953b7e0535e432cb83f65edda37e6983 Solved this problem
