### ISSUE TITLE
`erg pack` and subcommands returns an error: `Error: poise is not installed`

### ISSUE THREAD

**Issue by buster-blue** [erg-lang/erg#506]
### Describe the bug?

When I try to use erg's pack commands, it simply outputs an error message `Error: poise is not installed`. None of the commands do anything else, and it gives no more useful info.

### Reproducible code

`erg pack init`

### Expected result

It works, or if it doesn't work, it gives me more info on what poise is and how to install it.

### Actual result

output `Error: poise is not installed`

### Additional context

I installed it with `cargo install erg --features full` so it's the full-featured build

### Erg version

Erg 0.6.35

### Python version

Python3.11

### OS

Linux (other distro)

**Comment by mtshiba** [comment]
Actually, `erg pack` is just an alias for `poise`. The package manager, poise is not integrated with the compiler, so it must be installed separately.
You can easily install it using [ergup](https://github.com/mtshiba/ergup).
