### ISSUE TITLE
Put a badge on all translated documents

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#51]
Continuation from https://github.com/erg-lang/erg/issues/48.

A badge indicating the translation status should be attached to all translated documents.

The format of the badge is as follows.

```
[![badge](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fgezf7g7pd5.execute-api.ap-northeast-1.amazonaws.com%2Fdefault%2Fsource_up_to_date%3Fowner%3Derg-lang%26repos%3Derg%26ref%3Dmain%26path%3{ORIGINAL_FILE_NAME}%26commit_hash%3D{ORIGINAL_COMMIT_HASH})
](https://gezf7g7pd5.execute-api.ap-northeast-1.amazonaws.com/default/source_up_to_date?owner=erg-lang&repos=erg&ref=main&path={ORIGINAL_FILE_NAME}&commit_hash={ORIGINAL_COMMIT_HASH})
```

Replace {ORIGINAL_FILE_NAME} and {ORIGINAL_COMMIT_HASH} with the appropriate ones.

As an example, here is the badge of `README_zh-CN.md`. The original one is `README.md`.
{ORIGINAL_FILE_NAME} = README.md
{ORIGINAL_HASH} = 47b9b758acea9d4ea5d618436935b197636074f6
The result is as follows.

```
[![badge](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fgezf7g7pd5.execute-api.ap-northeast-1.amazonaws.com%2Fdefault%2Fsource_up_to_date%3Fowner%3Derg-lang%26repos%3Derg%26ref%3Dmain%26path%3DREADME.md%26commit_hash%3D47b9b758acea9d4ea5d618436935b197636074f6)
](https://gezf7g7pd5.execute-api.ap-northeast-1.amazonaws.com/default/source_up_to_date?owner=erg-lang&repos=erg&ref=main&path=README.md&commit_hash=47b9b758acea9d4ea5d618436935b197636074f6)
```

The badge should be placed directly below the document title.

The documents under [doc/EN](https://github.com/erg-lang/erg/tree/main/doc/EN) are the ones I have not yet finished putting badges on. The original is located under [doc/JA](https://github.com/erg-lang/erg/tree/main/doc/JA).

**Comment by mtshiba** [comment]
Badges should be checked to ensure that they are linked correctly; VSCode's markdown preview, for example, can be used to preview that the badge is functioning properly.

**Comment by C-BJ** [comment]
You should migrate Japanese documents to English as soon as possible and set English documents as the initial documents, because people will prefer to start translating from English documents rather than Japanese documents. @mtshiba

**Comment by mtshiba** [comment]
OK, we should also set up an issue to translate the Japanese document into English.
