### ISSUE TITLE
Change Erg's introduction text on the right side of the Github page and README

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#53]
Now: A Python-compatible statically typed language
Suggested Changes: A general-purpose statically typed language that can interoperate seamlessly with Python

Why: 
1.`Python compatibility` is ambiguous 
2.Erg's niche market should be bigger than Python's, so to prevent misunderstandings, add generic embellishments

**Comment by mtshiba** [comment]
I, too, am wondering if there is a better phrase than "A Python-compatible statically typed language", but "A general-purpose statically typed language that can interoperate seamlessly with Python" is not sufficient, I think.

There are already languages that can be called Python, such as Julia. People who see the above explanation may think, "Oh, there's another one like Julia? That's enough" (However, Julia can only bind to Python and cannot achieve static typing of the Python APIs, which is one of Erg's goals).

And it is probably true that Erg's niche is larger than Python's.
Erg has plans to develop backends other than Python (e.g. LLVM, Wasm). If that happens, this introduction text will have to be rethought from scratch.

For now, I am trying to be catchier than accurate.

**Comment by C-BJ** [comment]
What about: A general-purpose statically typed language that can deeply improve the Python ecosystem
@mtshiba

**Comment by mtshiba** [comment]
I would like to hear several opinions.

**Comment by mtshiba** [comment]
It was a little long, so I deleted `general-purpose` part.
Now, I have updated the introductory text.
