### ISSUE TITLE
Messy code when using Chinese display week

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#55]
![image](https://user-images.githubusercontent.com/62678643/185351903-80d4d6d8-863c-4310-bb4e-dcaeb6a2ee53.png)

**Comment by mtshiba** [comment]
This problem https://github.com/erg-lang/erg/issues/45#issuecomment-1218065146. I am trying to determine the cause, and it seems that it is a character code issue.

**Comment by C-BJ** [comment]
![image](https://user-images.githubusercontent.com/62678643/185651970-3527cc42-c79e-4d56-b3c8-798a71e22af3.png)
![image](https://user-images.githubusercontent.com/62678643/185652312-78bcc50f-f8a4-43f2-b3e2-8aa4e21d7bb5.png)

**Comment by toddlerer** [comment]
I would prefer to display UTC in ISO 8601.
On Linux and macOS, the command `date -u +%Y-%m-%dT%H:%MZ` will output something like `2022-08-19T23:50Z`.
