### ISSUE TITLE
In REPL, if you can determine that an error has occurred on one line, you should not start a new line

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#58]
![image](https://user-images.githubusercontent.com/62678643/185360484-dbc323d8-2d4d-460a-96dd-ee673aa2d716.png)

Here it should probably just report the error instead of starting a new line

**Comment by mtshiba** [comment]
It will be necessary to have `Parser` inspect the input to determine if it is invalid, valid, or needs to be continued.

**Comment by mtshiba** [comment]
Perhaps the option `NeedNextLine` should be added to `ErrorKind`: the REPL gives input to the parser, and when an error is returned, if the error type is `NeedNextLine`, it prompts for the next line of input.
