### ISSUE TITLE
One-step exit from REPL

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#59]
Now `-` causes the REPL to exit unexpectedly and directly, which is a bug, but can be borrowed for one-step exit from the REPL

**Comment by mtshiba** [comment]
This seems to be fixed at https://github.com/erg-lang/erg/commit/3314825fc19d5a0bae1e264b88b29c0e62cd9741.

**Comment by C-BJ** [comment]
This is actually a proposal to let quit() and Ctrl + Z exit the REPL in one step without having to press Enter again
@mtshiba

**Comment by mtshiba** [comment]
You can exit by `:exit`.

**Comment by mtshiba** [comment]
And I fixed to exit correctly when `quit()` or something is called.

https://github.com/erg-lang/erg/commit/1078345a98d72d678aea590d0529956bc49f9750
