### ISSUE TITLE
Enter nothing in REPL or just type space should just clear the current line without doing anything

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#60]
For the first case, there should be no response from REPL, rather than reopening a new line for input

For the second case it should be like the first case, except that the input spaces are deleted

Continue https://github.com/erg-lang/erg/issues/56 because it was not really done

**Comment by C-BJ** [comment]
This is not actually an accidental act, but a functional suggestion @mtshiba

**Comment by mtshiba** [comment]
Now the input can be cleared by typing `:clear` (note that this does not reset the execution state).
Empty code is enabled as a program that does nothing.
