### ISSUE TITLE
Incorrect REPL tips

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#62]
![image](https://user-images.githubusercontent.com/62678643/185391465-c914c736-e377-418b-8ff1-62fabbd4b3b4.png)

**Comment by mtshiba** [comment]
What command or script did you run to get this result?

**Comment by C-BJ** [comment]
> What command or script did you run to get this result?

Windows 11
Powershell 7.2.6

![image](https://user-images.githubusercontent.com/62678643/185522229-85410633-1980-466a-b068-d3b4258cf8c4.png)

**Comment by mtshiba** [comment]
It's Python, not Erg, that's showing this.
It might be better to make the same behavior in Erg.
