### ISSUE TITLE
Issue, PR and commit templates

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#76]
These templates would be very helpful.
Even if a template is not needed now, it will be easier to manage in the future as the number of contributors increases.

## Issue and PR
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

## commit template
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by C-BJ** [comment]
Also ![image](https://user-images.githubusercontent.com/62678643/185790336-a711e0ed-4519-42ee-8059-76068b49356a.png)

**Comment by mtshiba** [comment]
I created issue & PR templates (though it is a simple one).

**Comment by mtshiba** [comment]
And I enabled content reports.

**Comment by mtshiba** [comment]
May I close it?
