### ISSUE TITLE
In Windows, panicked at python not found

### ISSUE THREAD

**Issue by GreasySlug** [erg-lang/erg#8]
## Python3
version 3.10.4

## I tried
```sh
git clone url
cargo run
```
## Error log
Starting the REPL server...
thread 'main' panicked at 'cannot execute python: Error { kind: NotFound, message: "program not found" }', compiler\erg_common\python_util.rs:114:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\erg.exe` (exit code: 101)

I think that cmd, powershll and PowerShell have no `which` command

So I recommend this crate https://docs.rs/which/latest/which/

**Comment by mtshiba** [comment]
I'd like to develop with zero dependencies on external crates (although it's not a strong commitment that I'm absolutely not willing to compromise).

Can `where.exe` be used instead for Windows?

**Comment by GreasySlug** [comment]
>I'd like to develop with zero dependencies on external crates (although it's not a strong commitment that I'm absolutely not willing to compromise).

Indeed, you are creating a new language.

> Can where.exe be used instead for Windows?

I haven't tried it, but it should work.
and also `powershell` and `PowerShell` would be able to use `(gcm python).Definition`

**Comment by mtshiba** [comment]
Apparently this is not a very difficult problem.

I am busy fixing a bug in the type inference system right now, so I will work on this issue later.

Or if someone could send me a PR, I would be very grateful...
