### ISSUE TITLE
Cannot open multiple REPLs at once

### ISSUE THREAD

**Issue by ytoml** [erg-lang/erg#85]
**Describe the bug**
When we try to open multiple REPL, it reports `OSError: [Errno 48] Address already in use`.

**Reproducible code**
Try to run more than one `erg` at once.

**Expected behavior**
Different port is automatically assigned and REPL server is up.

**Screenshots (optional)**
For example, with tmux:
<img width="668" alt="スクリーンショット 2022-08-27 0 59 44" src="https://user-images.githubusercontent.com/54735373/186945733-dc5253c0-848f-4427-8e74-a46077bea0e3.png">

**Comment by ytoml** [comment]
We should adding some port checking procedures
around line 32 in `src/dummy.rs`:
```Rust
println!("Starting the REPL server...");
let code = include_str!("scripts/repl_server.py");
exec_py(code);
println!("Connecting to the REPL server...");
```

Easy workaround may be:
```Python
# repl_server.py: line 8
__server_socket.bind(('0.0.0.0', __PORT__))
```
and replace `__PORT__` in `dummy.rs` like:
```Rust
let found_port = /* some port checking procedures */;
let code = include_str!("scripts/repl_server.py").replace("__PORT__", found_port.to_string().as_str());
```
but I'm not confident it's a smart way to inject port to python script.

**Comment by mtshiba** [comment]
I think the method is the way to go.
